services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sabana_pasajes
      POSTGRES_USER: sabana_user
      POSTGRES_PASSWORD: sabana_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
